# Generated by Django 4.2.7 on 2023-11-19 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="student_ticket",
                to="api.user",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="tutor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tutor_ticket",
                to="api.user",
            ),
        ),
    ]
