# Generated by Django 4.2.7 on 2024-03-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="issues",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="semester",
            managers=[],
        ),
        migrations.AlterField(
            model_name="announcement",
            name="end_date",
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="start_date",
            field=models.DateField(blank=True),
        ),
    ]
