# Generated by Django 4.2.7 on 2023-12-07 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_ticket_student_alter_ticket_tutor"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="difficulty",
            field=models.CharField(
                blank=True,
                choices=[("EASY", "Easy"), ("MEDIUM", "Medium"), ("HARD", "Hard")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="was_flagged",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="tutor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assistant_tutor_ticket",
                to="api.user",
            ),
        ),
    ]
