# Generated by Django 4.2.7 on 2023-12-07 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_ticket_difficulty_ticket_was_flagged_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="asst_tutor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assistant_tutor_ticket",
                to="api.user",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="tutor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tutor_ticket",
                to="api.user",
            ),
        ),
    ]
