from api.models.user import User

data = [
    {
        "name": "Stacey Rodriguez",
        "student_nuid": "32429909",
        "email": "StaceyRodriguez@unomaha.edu",
        "is_tutor": False,
        "is_admin": False,
        "MSOID": "49148305",
    },
    {
        "name": "Sandra Murillo",
        "student_nuid": "72973844",
        "email": "SandraMurillo@unomaha.edu",
        "is_tutor": False,
        "is_admin": False,
        "MSOID": "08070241",
    },
    {
        "name": "Rachael Cooper",
        "student_nuid": "61097995",
        "email": "RachaelCooper@unomaha.edu",
        "is_tutor": False,
        "is_admin": False,
        "MSOID": "95543505",
    },
    {
        "name": "Christopher Jones",
        "student_nuid": "39914927",
        "email": "ChristopherJones@unomaha.edu",
        "is_tutor": False,
        "is_admin": False,
        "MSOID": "77115188",
    },
    {
        "name": "Robin Wallace",
        "student_nuid": "29183692",
        "email": "RobinWallace@unomaha.edu",
        "is_tutor": False,
        "is_admin": False,
        "MSOID": "55144506",
    },
    {
        "name": "Tammy Ortiz",
        "student_nuid": "43825707",
        "email": "TammyOrtiz@unomaha.edu",
        "is_tutor": False,
        "is_admin": False,
        "MSOID": "30894808",
    },
    {
        "name": "Sean Lester",
        "student_nuid": "83185892",
        "email": "SeanLester@unomaha.edu",
        "is_tutor": False,
        "is_admin": False,
        "MSOID": "25643503",
    },
    {
        "name": "Bryan Williams",
        "student_nuid": "78336070",
        "email": "BryanWilliams@unomaha.edu",
        "is_tutor": False,
        "is_admin": False,
        "MSOID": "33782263",
    },
    {
        "name": "Mark Martinez",
        "student_nuid": "19649566",
        "email": "MarkMartinez@unomaha.edu",
        "is_tutor": False,
        "is_admin": False,
        "MSOID": "05093335",
    },
    {
        "name": "Catherine Gonzalez",
        "student_nuid": "06369040",
        "email": "CatherineGonzalez@unomaha.edu",
        "is_tutor": False,
        "is_admin": False,
        "MSOID": "79973014",
    },
    {
        "name": "Timothy Rodgers",
        "student_nuid": "18685480",
        "email": "TimothyRodgers@unomaha.edu",
        "is_tutor": False,
        "is_admin": False,
        "MSOID": "94504002",
    },
    {
        "name": "Mary Campbell",
        "student_nuid": "70341362",
        "email": "MaryCampbell@unomaha.edu",
        "is_tutor": False,
        "is_admin": False,
        "MSOID": "67737758",
    },
    {
        "name": "Todd Williams",
        "student_nuid": "86440936",
        "email": "ToddWilliams@unomaha.edu",
        "is_tutor": False,
        "is_admin": False,
        "MSOID": "62980104",
    },
    {
        "name": "Michaela Harris",
        "student_nuid": "94392425",
        "email": "MichaelaHarris@unomaha.edu",
        "is_tutor": False,
        "is_admin": False,
        "MSOID": "32914313",
    },
    {
        "name": "Kathleen Brooks",
        "student_nuid": "19960081",
        "email": "KathleenBrooks@unomaha.edu",
        "is_tutor": False,
        "is_admin": False,
        "MSOID": "51603984",
    },
    {
        "name": "Alexander Wu",
        "student_nuid": "40540825",
        "email": "AlexanderWu@unomaha.edu",
        "is_tutor": False,
        "is_admin": False,
        "MSOID": "35967682",
    },
    {
        "name": "Paige Howard",
        "student_nuid": "10469026",
        "email": "PaigeHoward@unomaha.edu",
        "is_tutor": False,
        "is_admin": False,
        "MSOID": "72103487",
    },
    {
        "name": "Cory Allen",
        "student_nuid": "08508751",
        "email": "CoryAllen@unomaha.edu",
        "is_tutor": False,
        "is_admin": False,
        "MSOID": "05175246",
    },
    {
        "name": "Paul Mercado",
        "student_nuid": "95569307",
        "email": "PaulMercado@unomaha.edu",
        "is_tutor": False,
        "is_admin": False,
        "MSOID": "53581259",
    },
    {
        "name": "Renee Sanders",
        "student_nuid": "31646307",
        "email": "ReneeSanders@unomaha.edu",
        "is_tutor": False,
        "is_admin": False,
        "MSOID": "63682434",
    },
    {
        "name": "Jose May",
        "student_nuid": "40736716",
        "email": "JoseMay@unomaha.edu",
        "is_tutor": False,
        "is_admin": False,
        "MSOID": "43360970",
    },
    {
        "name": "Linda Mcdonald",
        "student_nuid": "31662604",
        "email": "LindaMcdonald@unomaha.edu",
        "is_tutor": False,
        "is_admin": False,
        "MSOID": "14121241",
    },
    {
        "name": "Jerome Rodriguez",
        "student_nuid": "06488321",
        "email": "JeromeRodriguez@unomaha.edu",
        "is_tutor": False,
        "is_admin": False,
        "MSOID": "35879930",
    },
    {
        "name": "Kimberly Fisher",
        "student_nuid": "78391598",
        "email": "KimberlyFisher@unomaha.edu",
        "is_tutor": False,
        "is_admin": False,
        "MSOID": "80157106",
    },
    {
        "name": "Lisa Perez",
        "student_nuid": "31454223",
        "email": "LisaPerez@unomaha.edu",
        "is_tutor": False,
        "is_admin": False,
        "MSOID": "90150012",
    },
    {
        "name": "Vickie Phillips",
        "student_nuid": "24850919",
        "email": "VickiePhillips@unomaha.edu",
        "is_tutor": False,
        "is_admin": False,
        "MSOID": "37809256",
    },
    {
        "name": "Jeffrey Herrera",
        "student_nuid": "03100851",
        "email": "JeffreyHerrera@unomaha.edu",
        "is_tutor": False,
        "is_admin": False,
        "MSOID": "81784516",
    },
    {
        "name": "Michelle Gallagher",
        "student_nuid": "58436462",
        "email": "MichelleGallagher@unomaha.edu",
        "is_tutor": False,
        "is_admin": False,
        "MSOID": "47161337",
    },
    {
        "name": "Brian Larson",
        "student_nuid": "48046688",
        "email": "BrianLarson@unomaha.edu",
        "is_tutor": False,
        "is_admin": False,
        "MSOID": "03158760",
    },
    {
        "name": "Rachael Jackson",
        "student_nuid": "28544975",
        "email": "RachaelJackson@unomaha.edu",
        "is_tutor": False,
        "is_admin": False,
        "MSOID": "86189606",
    },
    {
        "name": "Hailey West",
        "student_nuid": "71266084",
        "email": "HaileyWest@unomaha.edu",
        "is_tutor": False,
        "is_admin": False,
        "MSOID": "40102153",
    },
    {
        "name": "Michelle Bell",
        "student_nuid": "01324020",
        "email": "MichelleBell@unomaha.edu",
        "is_tutor": False,
        "is_admin": False,
        "MSOID": "59043157",
    },
    {
        "name": "Emily Grant",
        "student_nuid": "23335110",
        "email": "EmilyGrant@unomaha.edu",
        "is_tutor": False,
        "is_admin": False,
        "MSOID": "90233678",
    },
    {
        "name": "Tracey Johnson",
        "student_nuid": "59529507",
        "email": "TraceyJohnson@unomaha.edu",
        "is_tutor": False,
        "is_admin": False,
        "MSOID": "23260931",
    },
    {
        "name": "James Armstrong",
        "student_nuid": "28039211",
        "email": "JamesArmstrong@unomaha.edu",
        "is_tutor": False,
        "is_admin": False,
        "MSOID": "68104276",
    },
    {
        "name": "Karen Walls",
        "student_nuid": "05685806",
        "email": "KarenWalls@unomaha.edu",
        "is_tutor": False,
        "is_admin": False,
        "MSOID": "50684700",
    },
    {
        "name": "Richard Jackson",
        "student_nuid": "28775317",
        "email": "RichardJackson@unomaha.edu",
        "is_tutor": False,
        "is_admin": False,
        "MSOID": "43962341",
    },
    {
        "name": "Leah Gutierrez",
        "student_nuid": "16260696",
        "email": "LeahGutierrez@unomaha.edu",
        "is_tutor": False,
        "is_admin": False,
        "MSOID": "57344058",
    },
    {
        "name": "David Kelley",
        "student_nuid": "84248992",
        "email": "DavidKelley@unomaha.edu",
        "is_tutor": False,
        "is_admin": False,
        "MSOID": "51348397",
    },
    {
        "name": "Kristin Smith",
        "student_nuid": "87403817",
        "email": "KristinSmith@unomaha.edu",
        "is_tutor": False,
        "is_admin": False,
        "MSOID": "19444086",
    },
    {
        "name": "Cindy Watkins",
        "student_nuid": "80240532",
        "email": "CindyWatkins@unomaha.edu",
        "is_tutor": False,
        "is_admin": False,
        "MSOID": "68394578",
    },
    {
        "name": "Ariel Pitts",
        "student_nuid": "06967826",
        "email": "ArielPitts@unomaha.edu",
        "is_tutor": False,
        "is_admin": False,
        "MSOID": "11642749",
    },
    {
        "name": "Lauren Bentley",
        "student_nuid": "12211265",
        "email": "LaurenBentley@unomaha.edu",
        "is_tutor": False,
        "is_admin": False,
        "MSOID": "51603960",
    },
    {
        "name": "Brooke Gibson",
        "student_nuid": "19628448",
        "email": "BrookeGibson@unomaha.edu",
        "is_tutor": False,
        "is_admin": False,
        "MSOID": "78168343",
    },
    {
        "name": "Debra Bell",
        "student_nuid": "10793930",
        "email": "DebraBell@unomaha.edu",
        "is_tutor": False,
        "is_admin": False,
        "MSOID": "59370826",
    },
    {
        "name": "Jennifer Zimmerman",
        "student_nuid": "36746750",
        "email": "JenniferZimmerman@unomaha.edu",
        "is_tutor": False,
        "is_admin": False,
        "MSOID": "19485478",
    },
    {
        "name": "Sheila Cooper",
        "student_nuid": "62702041",
        "email": "SheilaCooper@unomaha.edu",
        "is_tutor": False,
        "is_admin": False,
        "MSOID": "01234619",
    },
    {
        "name": "Michael Estrada",
        "student_nuid": "96670163",
        "email": "MichaelEstrada@unomaha.edu",
        "is_tutor": False,
        "is_admin": False,
        "MSOID": "52967528",
    },
    {
        "name": "Nancy Obrien",
        "student_nuid": "20791742",
        "email": "NancyObrien@unomaha.edu",
        "is_tutor": False,
        "is_admin": False,
        "MSOID": "33977010",
    },
    {
        "name": "Justin Deleon",
        "student_nuid": "71210940",
        "email": "JustinDeleon@unomaha.edu",
        "is_tutor": False,
        "is_admin": False,
        "MSOID": "14496981",
    },
]


def loaddata():
    for i in data:
        user = User()
        user.name = i.get("name")
        user.student_nuid = i.get("student_nuid")
        user.email = i.get("email")
        user.is_tutor = False
        user.is_admin = False
        user.MSOID = i.get("MSOID")
        user.save()
        print("SAVED!")


def run():
    loaddata()
