# Generated by Django 4.2.4 on 2023-10-07 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_name", models.CharField(max_length=100)),
                ("course_id", models.CharField(max_length=25)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Dummy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("claimed", models.BooleanField(default=False)),
                ("closed", models.BooleanField(default=False)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("issue_type", models.CharField(blank=True, max_length=255)),
                ("name", models.CharField(max_length=25)),
                ("professor", models.CharField(max_length=50)),
                ("assignment", models.CharField(max_length=255)),
                ("course", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Hours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mondayOpen", models.TimeField()),
                ("mondayClose", models.TimeField()),
                ("tuesdayOpen", models.TimeField()),
                ("tuesdayClose", models.TimeField()),
                ("wednesdayOpen", models.TimeField()),
                ("wednesdayClose", models.TimeField()),
                ("thursdayOpen", models.TimeField()),
                ("thursdayClose", models.TimeField()),
                ("fridayOpen", models.TimeField()),
                ("fridayClose", models.TimeField()),
                ("saturdayOpen", models.TimeField()),
                ("saturdayClose", models.TimeField()),
                ("sundayOpen", models.TimeField()),
                ("sundayClose", models.TimeField()),
                ("mondayIsOpen", models.BooleanField(default=True)),
                ("tuesdayIsOpen", models.BooleanField(default=True)),
                ("wednesdayIsOpen", models.BooleanField(default=True)),
                ("thursdayIsOpen", models.BooleanField(default=True)),
                ("fridayIsOpen", models.BooleanField(default=True)),
                ("saturdayIsOpen", models.BooleanField(default=True)),
                ("sundayIsOpen", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Tutor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("is_working", models.BooleanField(default=False)),
                ("tutor_bio", models.TextField()),
                ("courses_tutoring", models.ManyToManyField(to="api.course")),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("started", models.BooleanField(default=False)),
                ("issue_type", models.CharField(max_length=100)),
                ("start_time", models.DateTimeField(null=True)),
                ("end_time", models.DateTimeField(null=True)),
                ("was_successful", models.BooleanField(default=False)),
                ("description", models.CharField(max_length=255)),
                ("comments", models.CharField(max_length=255)),
                (
                    "course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.course",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.professor",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.student",
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.tutor",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="professor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="api.professor"
            ),
        ),
    ]
