# Generated by Django 4.2.4 on 2023-09-03 22:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ticket",
            name="started",
            field=models.BooleanField(default=False),
        ),
    ]
