# Generated by Django 4.2.6 on 2023-10-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="modality",
            field=models.CharField(default="001", max_length=10),
        ),
    ]
