# Generated by Django 4.2.4 on 2023-10-08 05:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hours",
            options={"verbose_name_plural": "Hours"},
        ),
    ]
