# Generated by Django 4.2.4 on 2023-10-10 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="section",
            name="course",
        ),
        migrations.AlterField(
            model_name="section",
            name="modality",
            field=models.CharField(
                choices=[("Online", "850"), ("In-Person", "001"), ("Hybrid", "002")],
                default="In-Person",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="professor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.professor",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="tickets",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.ticket",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.course",
            ),
        ),
    ]
