# Generated by Django 4.2.6 on 2023-10-28 22:43

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("generic", django.db.models.manager.Manager()),
            ],
        ),
    ]
