# Generated by Django 4.2.4 on 2023-10-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dummy",
            old_name="started",
            new_name="claimed",
        ),
        migrations.AddField(
            model_name="dummy",
            name="closed",
            field=models.BooleanField(default=False),
        ),
    ]
