# Generated by Django 4.2.4 on 2023-09-06 01:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="courses",
        ),
    ]
