name: Backend

on:
  push:
    branches: ['**']
  pull_request:
    branches: [ "master" ]

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - name: Install Dependencies
        uses: actions/checkout@v3
      - working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip3 install poetry
          poetry config virtualenvs.create false
          poetry shell
          poetry install
      - name: Run Linting
        run: make lint
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - name: Install Dependencies
        uses: actions/checkout@v3
      - working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip3 install poetry
          poetry config virtualenvs.create false
          poetry shell
          poetry install
      - name: Run Tests
        run: make test-for-pipeline
  Typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - name: Install Dependencies
        uses: actions/checkout@v3
      - working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip3 install poetry
          poetry config virtualenvs.create false
          poetry shell
          poetry install
      - name: Run Typechecker
        run: make typecheck

