name: Test and lint frontend

on:
  push:
    branches: ['**']
  pull_request:
    branches: [ "main" ]

jobs:
  run-npm:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3
      - name: set up node
        uses: actions/setup-node@v3
        with:
            node-version: '18.17.1'
      - name: npm install
        uses: actions/checkout@v3
      - working-directory: ./frontend-ts
        run: |
          npm ci 
          npx eslint
