name: Nulzo Workflow

on:
  push:
    branches: ['**']
  pull_request:
    branches: [ "master" ]

jobs:
  install-poetry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up build
        run: |
          python -m pip install --upgrade pip
          pip3 install poetry
          poetry config virtualenvs.create false
          poetry shell
          poetry install

  build-project:
    runs-on: ubuntu-latest
    needs: install-poetry
    steps:
      - uses: actions/checkout@v3
      - name: Run Build Script
        run: |
          make build
          
  run-linter:
    runs-on: ubuntu-latest
    needs: build-project
    steps:
      - uses: actions/checkout@v3
      - name: Run Linting Script
        run: |
          make lint

  run-tests:
    runs-on: ubuntu-latest
    needs: build-project
    steps:
      - uses: actions/checkout@v3
      - name: Run Linting Script
        run: |
          make test
    
