name: CSLC CI/CD Workflow

on:
  push:
    branches: ['**']
  pull_request:
    branches: [ "master" ]

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - name: Install Dependencies
        uses: actions/checkout@v4
        with:
          path: backend
      - run: |
          python -m pip install --upgrade pip
          pip3 install poetry
          poetry config virtualenvs.create false
          poetry shell
          poetry install

  build-project:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v3
      - name: Run Build Script
        run: |
          echo testing

  # run-linter:
  #   runs-on: ubuntu-latest
  #   needs: build-project
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Run Linting Script
  #       run: |
  #         make lint

  # run-tests:
  #   runs-on: ubuntu-latest
  #   needs: build-project
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Run Linting Script
  #       run: |
  #         make test
    
