name: Makefile CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Pip / Configure Python
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Configure Poetry Environment
      run: |
        poetry config virtualenvs.create false
        make poetry

    - name: Run Linting
      run: |
        make lint

    - name: Run Tests
      run: |
        make test
